version: "3.10"

services:

  school-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: School-API
    command: python3 manage.py runserver 0.0.0.0:8000
    # volume here mounts the code to the container and updates 
    # the container each time there is a source code changes.
    # without volumn we have to rebuild the image each time
    # the source code changes.
    volumes:
      - .:/app
    # ports:
    #   - 8000:8000
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - postgres-db
    networks:
      - school-api-net

  postgres-db:
    image: kartoza/postgis:13.0
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: on-failure
    networks:
      - school-api-net

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: school_front
    volumes:
      - /app/node_modules
      - ./client:/app
    depends_on:
      - school-api
    networks:
      - school-api-net

  nginx:
    restart: always
    depends_on:
      - school-api
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 8080:80
    networks:
      - school-api-net

networks:
  school-api-net:
    driver: bridge

volumes:
  postgres_data: