# Generated by Django 3.1.5 on 2022-05-14 01:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='School Name')),
                ('province', models.CharField(choices=[('North Province', 'North Province'), ('East Province', 'East Province'), ('West Province', 'West Province'), ('South Province', 'Southprovince'), ('Kigali City', 'Kigali City')], max_length=30, verbose_name='School Province')),
                ('district', models.CharField(max_length=40, verbose_name='School Disctrict')),
                ('level', models.CharField(choices=[('Pre-Nursery', 'Pre-Nursery'), ('Nursery', 'Nursery'), ('Primary', 'Primary'), ('General Secondary', 'General Secondary'), ('TVET', 'TVET'), ('General Tertiary', 'General Tertiary'), ('Adult Literacy', 'Adult Literacy')], max_length=50, verbose_name='School Level')),
                ('male', models.IntegerField(default=0, verbose_name='Number of Male Students')),
                ('female', models.IntegerField(default=0, verbose_name='Number of Female Students')),
                ('electricity_availability', models.BooleanField(default=False)),
                ('school_code', models.IntegerField(default=0)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
