# Generated by Django 3.1.5 on 2022-05-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='electricity_availability',
            new_name='capacity_availability',
        ),
        migrations.RemoveField(
            model_name='school',
            name='province',
        ),
        migrations.AddField(
            model_name='school',
            name='community',
            field=models.CharField(choices=[('Dalhousie', 'Dalhousie'), ('Edgement', 'Edgement'), ('Brent Wood', 'Brent Wood'), ('Arbour Lake', 'Arbour Lakee'), ('Varsity', 'Varsity')], default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='level',
            field=models.CharField(choices=[('Pre-School', 'Pre-School'), ('Elementry', 'Elementry'), ('Junior High', 'Junior High'), ('Senior High', 'Senior High')], max_length=50, verbose_name='School Level'),
        ),
    ]
