# Generated by Django 3.1.5 on 2022-05-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20220516_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='capacity_availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='district',
            field=models.CharField(blank=True, max_length=40, verbose_name='School Disctrict'),
        ),
    ]
